### PR TITLE
[[7639]] log SG API calls to influx

### PR DESCRIPTION
**Pull request by kmcharlton**
Any qualms? I'm trying to never prevent the API call from actually going through, so hopefully I've wrapped enough try/excepts on top of each other to accomplish that :P 

If you want to try it out, you can just prepend this version of the SG API to your PYTHONPATH and then check out the dashboard in Grafana to see your calls:
http://metrics01.atomicfiction.com:3000/d/mwqPIiMik/shotgun-api-calls

There's some data I'm not actually capturing in Influx yet (filters, return fields, etc) but I figure host/user/pid/jid/etc will get us a lot better insights than we have currently.

### CODE REVIEW

**Review by CarineAtomic — COMMENTED** [review]
- Could we put that in our `afpipe.sg` module instead of changing the SG api ?
- Should we use `inspect` to log the calling module ? I feel it might be more useful than the process name
- Should we setup an easy way to toggle this on / off ?

**Comment by kmcharlton** [comment]
In order of the bullets:
* what's the benefit? we're already running a modified SG API anyway... plus then we won't log calls that people are making if they're importing the shotgun API directly instead of using our wrapper (I've definitely seen it before)
* yeah, let me see if I can do this quickly (I'd like to get this out today if possible since we're still having issues... ) 
* any ideas about how we'd do that? I can't think of anything besides Config that would allow us to easily toggle on/off and I don't want to put another dependency on our stuff in here... 🤔

**Comment by CarineAtomic** [comment]
The more mods we add in here, the more difficult / cumbersome it is to update from the official release ;)
But you're right, I hadn't realized our event plugins are not using `afpipe.sg`, so forget that comment...

For the toggle, maybe use an `AF_LOG_SG_CALLS` env var or something ? Or maybe just have a  constant in here that would be easy to switch from True to False.

**Comment by cmartinaf** [comment]
An environment variable such as AF_LOG_SG_CALLS as Carine suggested would be my preference. We can then add into the Begin.package in env

**Comment by kmcharlton** [comment]
Yeah, I guess I was thinking that to modify the env across the board, we'd have to release `env` but I guess it does make sense to have this available either way. I've added it and the module names. :)

**Comment by CarineAtomic** [comment]
The only issue I see with the env var is with people using old shells ;)

Changes look good to me !

**Review by cmartinaf — APPROVED** [review]

**Pull request merged**
